### ISSUE TITLE
require('pdfmake-browserified') error

### ISSUE THREAD

**Issue by moisesramalho** [xErik/pdfmake-browserified#1]
Hello. 

I've just installed pdfmake-browserified via npm and it's dependencies on a Node.js server running Sails.js framework, and when I declare the require in the controller I get the following error:

/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:2
typeof navigator||!/MSIE [1-9]\./.test(navigator.userAgent)){var t=e.document,
                                                                    ^
TypeError: Cannot read property 'document' of undefined
    at saveAs (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:2:232)
    at Object.<anonymous> (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:2:2499)
    at s (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:1:685)
    at /root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:1:736
    at Object.<anonymous> (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:267:202)
    at Object.../libs/fileSaver (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:268:4)
    at s (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:1:685)
    at e (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:1:856)
    at /root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:1:874
    at a (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:1:150)
    at Object.<anonymous> (/root/newP/node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js:1:387)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Am I missing something?
Thanks in advance.

**Comment by xErik** [comment]
I do not know Sails, so I am making assumptions here. 

According to the documentation, it looks like the Sails-controller is located server-side.

But, `pdfmake-browserified` is executed in the browser, hence the name. The pdf rendering takes place in the browser. However, `pdfmake` states that server-side rendering is possible, too, but I do not know anything about that.

The error `TypeError: Cannot read property 'document' of undefined` probably occurs, as the server does not know a `window.document`.

Let me know, if I am wrong about Sails. I will then look into it.

**Comment by moisesramalho** [comment]
Thnx @xErik, you're completly right about Sails and I'm indeed trying to use it server-side. 

Allready requested some help on the issue that brought me to pdfmaker-browserified (https://github.com/bpampuch/pdfmake/issues/317) and I believe it's on the way.. :)

Nice work on pdfmake-browserified anyway! ;)
